spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Qxsj?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  useSSL: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

